import { COLT_CHARACTERS } from '@zuychin-arcade/types';
import { RulesReferenceSheet, type RuleSection } from '../ui/RulesReferenceSheet';
import { COLT as C } from '../../constants/theme';
import { coltLeaveMessage } from './decision';
import { ColtRulesGuide } from './RulesGuide';
const colt:RuleSection[]=[{title:'The robbery',icon:'train',entries:[{title:'Five rounds',body:'Four random Round cards from the correct player-count deck are followed by one random Station card. Their printed turns control face-up, tunnel, speed-up, and counter-clockwise programming.'},{title:'Deck pollution',body:'A normal bandit deck starts with ten actions. Bullets received are useless cards shuffled into later hands. Drawing three cards may replace any one programming action.'}]},{title:'Six actions',icon:'cards-playing-outline',entries:[{title:'Move and floor',body:'Inside movement is one adjacent car. Roof movement is one to three cars. Floor changes between inside and roof in the current car.'},{title:'Shoot and punch',body:'Inside shots hit an adjacent car; roof shots hit the nearest visible bandit in either direction. Punch a bandit in your space, make that bandit drop loot, then move them to an adjacent car.'},{title:'Rob and Marshal',body:'Rob one loot token in your exact space. Move the Marshal one car inside. Bandits meeting him flee to the roof and receive neutral bullets if enough remain for the affected group.'}]},{title:'Official two-player teams',icon:'account-group-outline',entries:[{title:'Two bandits and 11 cards',body:'Each player controls a paired team of two bandits and both character powers apply. Keep each bandit’s loot separately. Secretly choose which starts in the caboose; the other starts in the next car.'},{title:'Reserve and Cover',body:'Before each shuffle, reserve one chosen card, then draw six more (seven with Doc). On a standard turn, immediately after programming Shoot, you may Cover it with a non-Marshal action belonging to your other bandit.'},{title:'Team Gunslinger',body:'Count all shots fired at the opposing team; shots into your teammate do not count. The tied highest-shooting team or teams gain $1000.'}]},{title:'Winning',icon:'cash-multiple',entries:[{title:'Loot values',body:'Purses are hidden values, jewels are $500, and strongboxes are $1000. In team play, combine both bandits’ loot at the end.'},{title:'Final tie',body:'After round five add loot and the Gunslinger prize. Highest wealth wins; among tied bandits or teams, fewer received bullets wins, then victory is shared.'}]}];
export function ColtReferenceSheet({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  return <RulesReferenceSheet visible={visible} onClose={onClose} gameTitle="Colt Express" subtitle="2016 base game · 2–6 players · two-bandit teams for two players" icon="train"
    palette={{ background: C.bg, surface: C.surface, panel: C.panel, border: C.border, accent: C.ember, secondary: C.gold, muted: C.muted, text: C.text }}
    sections={[...colt, { title: 'Your bandit powers', icon: 'account-star-outline', entries: Object.values(COLT_CHARACTERS).map(character => ({ title: character.name, body: character.summary })) },
    { title: 'Digital tablekeeping', icon: 'connection', entries: [
      { title: 'Supported setup', body: 'Non-Expert 2016 base game. Two players use two-bandit teams; the optional three-player two-bandit variant is not included. Three to six players choose from the available characters before the robbery. Character claims are public and unique; the first accepted claim takes that character.' },
      { title: 'Finite neutral bullets', body: 'The shared neutral-bullet supply is finite. If it cannot cover every bandit affected by the same event, nobody in that group receives a bullet. Marshal encounters still send bandits to the roof.' },
      { title: 'Programming is a commitment', body: 'A normal action-card button immediately submits your card. It resolves later in the shared program, when positions and available targets may have changed. The table offers exact legal execution choices. A two-bandit Shoot may first open optional Cover choices; Cancel does not submit either card.' },
      { title: 'Private information', body: 'Your hand, reserve and owned purse values are private. Face-down program cards conceal both the action and its bandit until execution. Public train loot shows its type, but purse values stay hidden.' },
      { title: 'Temporary connection loss', body: 'Your seat can reconnect during its grace period. Controls stay unavailable until your public train and private hand are restored together.' },
      { title: 'Leaving during a robbery (digital rule)', body: coltLeaveMessage() },
      { title: 'Completed results and rematches', body: 'Leaving a completed robbery does not change its result. A rematch needs at least two connected seats and no seat awaiting reconnection or expiry of reconnect grace.' },
    ] }]}><ColtRulesGuide /></RulesReferenceSheet>;
}
