import type { BangCardName, BangCharacterId } from './bang';
export const BANG_MIN_PLAYERS = 4;
export const BANG_MAX_PLAYERS = 7;
export const BANG_RULES_VERSION = 'fourth-edition-base-faq-2025-digital-v2';
export const BANG_CARD_COUNTS: Record<BangCardName, number> = { bang:25, missed:12, beer:6, saloon:1, stagecoach:2, wells_fargo:1, general_store:2, panic:4, cat_balou:4, gatling:1, indians:2, duel:3, barrel:2, dynamite:1, scope:1, mustang:2, jail:3, volcanic:2, schofield:3, remington:1, rev_carabine:1, winchester:1 };
export const BANG_WEAPON_RANGE: Partial<Record<BangCardName, number>> = { volcanic:1, schofield:2, remington:3, rev_carabine:4, winchester:5 };
export const BANG_CHARACTERS: Record<BangCharacterId, {name:string;health:3|4;summary:string}> = {
  bart_cassidy:{name:'Bart Cassidy',health:4,summary:'Draw a card whenever you lose a life.'}, black_jack:{name:'Black Jack',health:4,summary:'Reveal the second draw; draw an extra card on hearts or diamonds.'}, calamity_janet:{name:'Calamity Janet',health:4,summary:'Use BANG! as Missed! and Missed! as BANG!.'}, el_gringo:{name:'El Gringo',health:3,summary:'Take a random card from a player who damages you.'}, jesse_jones:{name:'Jesse Jones',health:4,summary:'The first draw may come from another player.'}, jourdonnais:{name:'Jourdonnais',health:4,summary:'Always has a virtual Barrel.'}, kit_carlson:{name:'Kit Carlson',health:4,summary:'Look at three cards, keep two, return one.'}, lucky_duke:{name:'Lucky Duke',health:4,summary:'Draw two cards for checks and choose the result.'}, paul_regret:{name:'Paul Regret',health:3,summary:'Always has a virtual Mustang.'}, pedro_ramirez:{name:'Pedro Ramirez',health:4,summary:'The first draw may come from the discard pile.'}, rose_doolan:{name:'Rose Doolan',health:4,summary:'Always has a virtual Scope.'}, sid_ketchum:{name:'Sid Ketchum',health:4,summary:'Discard two cards to regain one life.'}, slab_the_killer:{name:'Slab the Killer',health:4,summary:'His BANG! requires two Missed! responses.'}, suzy_lafayette:{name:'Suzy Lafayette',health:4,summary:'Draw a card whenever your hand becomes empty.'}, vulture_sam:{name:'Vulture Sam',health:4,summary:'Collect cards from eliminated players.'}, willy_the_kid:{name:'Willy the Kid',health:4,summary:'May play any number of BANG! cards.'}
};
