const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');
const { Buffer } = require('node:buffer');

const mobileRoot = path.resolve(__dirname, '..');
const masterPath = path.join(mobileRoot, 'assets/zuychin-controller.svg');
const PINK = '#FF2E88';
const BACKGROUND = '#0B0716';
const rasterSpecs = [
  { file: 'assets/icon.png', size: 1024, fraction: 0.86, color: PINK, background: BACKGROUND },
  { file: 'assets/android-icon-foreground.png', size: 1024, fraction: 0.52, color: PINK },
  { file: 'assets/android-icon-monochrome.png', size: 1024, fraction: 0.52, color: '#FFFFFF' },
  { file: 'assets/favicon.png', size: 64, fraction: 0.86, color: PINK, background: BACKGROUND },
  { file: 'public/icons/icon-192.png', size: 192, fraction: 0.86, color: PINK, background: BACKGROUND },
  { file: 'public/icons/icon-512.png', size: 512, fraction: 0.86, color: PINK, background: BACKGROUND },
  { file: 'public/icons/maskable-512.png', size: 512, fraction: 0.62, color: PINK, background: BACKGROUND },
  { file: 'public/icons/apple-touch-icon.png', size: 180, fraction: 0.86, color: PINK, background: BACKGROUND },
];

function parseMaster(source) {
  const svg = source.replace(/\r\n/g, '\n').trim();
  assert(/^<svg\b[\s\S]*<\/svg>$/.test(svg), 'Master must be a standalone SVG');
  assert(!/<(?:script|image|foreignObject)\b|\b(?:href|onload)\s*=|<!DOCTYPE|url\(/i.test(svg), 'Master must contain only self-contained vector artwork');
  const match = svg.match(/^<svg\b[^>]*\bviewBox\s*=\s*(["'])([^"']+)\1/);
  assert(match, 'Master requires a viewBox');
  const values = match[2].trim().split(/[\s,]+/).map(Number);
  assert(values.length === 4 && values.every(Number.isFinite) && values[2] > 0 && values[3] > 0, 'Invalid master viewBox');
  assert(svg.includes('currentColor'), 'Master must retain a themeable currentColor fill');
  return { svg, viewBox: values.join(' '), aspect: values[2] / values[3] };
}

function squareSvg(master, { size, fraction, color, background }) {
  const width = size * fraction;
  const height = width / master.aspect;
  assert(height <= size && width <= size, 'Artwork exceeds square canvas');
  const nested = master.svg.replace(/^<svg\b([^>]*)>/, (_, attributes) => {
    const retained = attributes.replace(/\s(?:x|y|width|height|color|preserveAspectRatio)\s*=\s*(["'])[^"']*\1/g, '');
    return `<svg${retained} x="${(size - width) / 2}" y="${(size - height) / 2}" width="${width}" height="${height}" preserveAspectRatio="xMidYMid meet" color="${color}">`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">${background ? `<rect width="${size}" height="${size}" fill="${background}"/>` : ''}${nested}</svg>\n`;
}

function hash(bytes) { return createHash('sha256').update(bytes).digest('hex'); }

function textArtifacts(master, rasterBuffers) {
  const hashes = Object.fromEntries(rasterSpecs.map(({ file }) => [file, hash(rasterBuffers[file])]));
  return {
    'assets/favicon.svg': squareSvg(master, rasterSpecs[3]),
    'assets/zuychin-logo.svg': master.svg.replace(/^<svg\b/, `<svg color="${PINK}"`) + '\n',
    'constants/arcadeLogo.ts': '// Generated by scripts/generate-brand.cjs from assets/zuychin-controller.svg.\n'
      + `export const ARCADE_LOGO_SVG = ${JSON.stringify(master.svg)};\n`
      + `export const ARCADE_LOGO_ASPECT = ${master.aspect};\n`
      + `export const ARCADE_LOGO_ASSET_SHA256 = ${JSON.stringify(hashes, null, 2)} as const;\n`,
  };
}

function parseArgs(args) {
  let sharpModule;
  let check = false;
  for (let index = 0; index < args.length; index++) {
    if (args[index] === '--check' && !check) check = true;
    else if (args[index] === '--sharp-module' && !sharpModule && args[index + 1] && !args[index + 1].startsWith('--')) sharpModule = path.resolve(args[++index]);
    else throw new Error('Usage: node scripts/generate-brand.cjs --sharp-module <existing module path> [--check]');
  }
  assert(sharpModule, '--sharp-module is required; the generator never installs dependencies');
  return { sharpModule, check };
}

async function main(args) {
  const { sharpModule, check } = parseArgs(args);
  const sharp = require(sharpModule);
  const master = parseMaster(fs.readFileSync(masterPath, 'utf8'));
  // The entire mark rectangle fits the central 66dp-diameter circle on a 108dp layer.
  assert(Math.hypot(0.52, 0.52 / master.aspect) <= 66 / 108, 'Adaptive artwork rectangle exceeds safe circle');
  assert(Math.hypot(0.62, 0.62 / master.aspect) <= 0.8, 'PWA artwork rectangle exceeds maskable safe circle');
  const artifacts = {};
  for (const spec of rasterSpecs) {
    artifacts[spec.file] = await sharp(Buffer.from(squareSvg(master, spec))).png().toBuffer();
  }
  Object.assign(artifacts, textArtifacts(master, artifacts));
  if (check) {
    for (const [file, bytes] of Object.entries(artifacts)) {
      assert(fs.readFileSync(path.join(mobileRoot, file)).equals(Buffer.from(bytes)), `Generated asset drift: ${file}`);
    }
  } else {
    for (const [file, bytes] of Object.entries(artifacts)) {
      fs.mkdirSync(path.dirname(path.join(mobileRoot, file)), { recursive: true });
      fs.writeFileSync(path.join(mobileRoot, file), bytes);
    }
  }
  console.log(JSON.stringify({ mode: check ? 'checked' : 'generated', master: 'assets/zuychin-controller.svg', files: Object.keys(artifacts), sharp: sharp.versions.sharp }));
}

module.exports = { parseMaster, squareSvg, textArtifacts, parseArgs, rasterSpecs, mobileRoot, masterPath };
if (require.main === module) main(process.argv.slice(2)).catch(error => { console.error(error.message); process.exitCode = 1; });
