import { LIBERTALIA_CREW } from '@zuychin-arcade/types';
import { RulesReferenceSheet, type RuleSection } from '../ui/RulesReferenceSheet';
import { LIBERTALIA as C } from '../../constants/theme';
import { libertaliaLeaveMessage } from './decision';
import { LibertaliaRulesGuide } from './RulesGuide';

const base: RuleSection[] = [{title:'Three voyages',icon:'ship-wheel',entries:[{title:'Shared crew information',body:'Each voyage adds the same six random crew ranks to every hand. Voyage lengths are four, five, then six days; unused crew remain in hand.'},{title:'Six-token reputation track',body:'All six colours occupy unique spaces, even with fewer than six players. A moving token shifts every token it passes; reputation gained beyond the right edge gains doubloons, while loss beyond the left edge costs them. Track position also gives 12–7 starting doubloons each voyage.'},{title:'Secret selection',body:'Everyone secretly chooses one crew member, then reveals together. Order low to high; reputation breaks equal ranks.'}]},{title:'Every day',icon:'weather-sunset',entries:[{title:'Daytime',body:'Resolve daytime powers from the leftmost, lowest-ranked crew to the right. Abilities are required unless they say you may.'},{title:'Dusk and loot',body:'Resolve characters right to left. First gain one available loot token, then resolve that character and token’s dusk abilities in your chosen order; a survivor then enters your ship.'},{title:'Two-player Midshipman',body:'A neutral rank 20.5 character joins the island. At its dusk position, the opponent of the character directly to its left removes one loot token before that character chooses.'},{title:'Night',body:'Resolve every night ability in each ship. If several belong to you, choose their order.'}]},{title:'Calm-side loot',icon:'treasure-chest',entries:[{title:'Dusk tokens',body:'A barrel gains 1 reputation. A saber discards another player’s character still on the island.'},{title:'Anchor tokens',body:'Chest +5; amulet +3; barrel +1; relic −3. A hook keeps one ship character for the next voyage or gains 2. Maps score each pair for 7 or each trio for 12; combine sets for the best total.'}]},{title:'Voyage end',icon:'anchor',entries:[{title:'Anchor and scoring',body:'Resolve character and loot anchor abilities in your chosen order, then add current doubloons to protected score. Return loot and send unkept ship crew to private graveyards.'},{title:'Winner',body:'After voyage three, highest score wins; the rightmost reputation token breaks a score tie.'}]}];

export function LibertaliaReferenceSheet({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  return <RulesReferenceSheet visible={visible} onClose={onClose} gameTitle="Libertalia" subtitle="Winds of Galecrest · calm-side loot · 2–6 admirals" icon="ship-wheel"
    palette={{ background: C.bg, surface: C.surface, panel: C.panel, border: C.border, accent: C.sky, secondary: C.gold, muted: C.muted, text: C.text }}
    sections={[...base, { title: 'Digital tablekeeping', icon: 'connection', entries: [
      { title: 'Wind Nymph clash timing (digital adaptation)', body: 'At the start of night, the table records which ships have Wind Nymph. If more than one does, each owner discards their own copy when resolving its ability, without gaining its doubloons. You keep your chosen order for your other night abilities.' },
      { title: 'Freed Prisoner timing (digital interpretation)', body: 'Freed Prisoner resolves at the end of night, after ordinary night abilities. An already chosen copy remains committed even if its source is later removed.' },
      { title: 'Empty hands', body: 'If your hand is empty, you sit out island selection without forfeiting. Your ship still resolves night and anchor abilities, and a new voyage adds six crew to your hand.' },
      { title: 'Losses and scoring', body: 'Night losses stop at zero. Anchor losses offset gains regardless of resolution order, so resolving a loss first cannot avoid its cost.' },
      { title: 'Private choices', body: 'Your hand and graveyard are private; ship crew, loot and scores are public. Choosing a card is local until you confirm it. You may change your secret selection until all admirals are ready and the crews reveal together. Required abilities use the exact legal options offered by the table.' },
      { title: 'Connection and departure', body: `A temporary disconnect retains reconnect grace. Leaving or allowing that grace to expire has the same effect. ${libertaliaLeaveMessage()}` },
      { title: 'Voyage setup after departure', body: 'Prepared loot and the player-count mode stay fixed for the current voyage. The next voyage adapts to the remaining active seats, including the neutral Midshipman if only two remain.' },
      { title: 'Completed results', body: 'Leaving after the result does not change completed participation or scores. A rematch requires at least two connected seats and no seat awaiting reconnection. Wait for reconnection or reconnect grace to expire.' },
    ] }, { title: 'All 40 crew', icon: 'cards-playing-outline', entries: LIBERTALIA_CREW.map(crew => ({ title: `#${crew.rank} · ${crew.name}`, body: `${crew.phases.join(' · ')}. ${crew.summary}` })) }]}><LibertaliaRulesGuide /></RulesReferenceSheet>;
}
